remote_server_uris = ["https://oxide-omicron-build.s3.amazonaws.com"]

[artifacts.alpine]
filename = "alpine.iso"
[artifacts.alpine.kind]
guest_os = "alpine"
[artifacts.alpine.source.remote_server]
sha256 = "ba8007f74f9b54fbae3b2520da577831b4834778a498d732f091260c61aa7ca1"

[artifacts.ovmf]
filename = "OVMF_CODE.fd"
kind = "bootrom"
[artifacts.ovmf.source.buildomat]
repo = "oxidecomputer/edk2"
series = "image_debug"
commit = "8c60ff4c271b0442b9a506a5cf9eab04cd5554aa"
sha256 = "9ce2266aaefb671a1977ddabb5155f8235be134f797e6c831abeb6c97c705569"
