local_root = "/tmp/phd-quickstart"
remote_root = "https://oxide-omicron-build.s3.amazonaws.com"

[guest_images.alpine]
guest_os_kind = "alpine"
metadata.relative_local_path = "alpine.iso"
metadata.expected_digest = "ba8007f74f9b54fbae3b2520da577831b4834778a498d732f091260c61aa7ca1"
metadata.relative_remote_path = "alpine.iso"

[bootroms.ovmf]
relative_local_path = "OVMF_CODE.fd"
expected_digest = "32b4ba73f302e6c1c1ebd7ed0fecab9fa1fcedac77765454aa91e66604c10d27"
relative_remote_path = "OVMF_CODE.fd"

