[package]
name = "viona_api-hdrchk"
version = "0.0.0"
license = "MPL-2.0"
build = "build.rs"
publish = false
edition = "2021"

[dependencies]
viona_api = { path = ".." }
libc = "0.2"

[build-dependencies]
cc = "1"
ctest2 = "0.4.7"

[[test]]
name = "main"
path = "test/main.rs"
harness = false
