[package]
name = "propolis-package"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "propolis-package"
test = false
doctest = false

[dependencies]
anyhow.workspace = true
indicatif.workspace = true
omicron-zone-package.workspace = true
tokio.workspace = true
